model_name: husky
cmd_topic_name: /husky_velocity_controller/cmd_vel

initial:
  x: 0.0
  y: 5.0
  phi: 0.0
   
target:
  x: 0.0
  y: -5.0  
  phi: 1.0

########################## YOU CAN CHANGE ANY PARAM BELOW ####################
###  you can modify the values below
###  you can also define maximum acceleration/deceleration, etc 

fbk_topic_name: /gazebo/model_states
lsr_topic_name: /front/scan
world: mud


update_frequency: 1000
min_distance_to_obstacles: 2.0

limit:
  speed: 0.5
  omega: 0.5

# Path planning
target_1:
  x:    5.0
  y:    0.0

target_2:
  x:    -2.0
  y:    -4.0

epsilon: 0.4